### ISSUE TITLE
Firebase has not been correctly initialized

### ISSUE THREAD

**Issue by Hekatoncheire** [Plasius/all_in_fest#3]
@Plasius amikor emulator-ban indítanám a projectet, jön a szokásos flutter error screen és egy core/initialization típusú errort dob, miszerint "firebase has not been correctly initialized, looks like you're using a firebase feature, before initialization" a hiba.
<img width="687" alt="Képernyőfotó 2022-03-28 - 15 36 20" src="https://user-images.githubusercontent.com/82810577/160409856-cab002f4-d4ac-490f-a441-63621db5cb4f.png">

**Comment by Plasius** [comment]
pod init
